/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as TeacherUploadRouteImport } from './routes/teacher.upload'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherQaRouteImport } from './routes/teacher.qa'
import { Route as LevelsLevelRouteImport } from './routes/levels.$level'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AdminQuestionBankRouteImport } from './routes/admin.question-bank'
import { Route as TeacherTestsIndexRouteImport } from './routes/teacher.tests.index'
import { Route as TeacherCoursesIndexRouteImport } from './routes/teacher.courses.index'
import { Route as TeacherClassesIndexRouteImport } from './routes/teacher.classes.index'
import { Route as AdminExamsIndexRouteImport } from './routes/admin.exams.index'
import { Route as TeacherTestsTestIdRouteImport } from './routes/teacher.tests.$testId'
import { Route as TeacherClassesClassIdRouteImport } from './routes/teacher.classes.$classId'
import { Route as AdminTestsNewRouteImport } from './routes/admin.tests.new'
import { Route as AdminExamsNewRouteImport } from './routes/admin.exams.new'
import { Route as AdminExamsExamIdRouteImport } from './routes/admin.exams.$examId'
import { Route as AdminExamsExamIdSubmissionsRouteImport } from './routes/admin.exams.$examId.submissions'

const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherUploadRoute = TeacherUploadRouteImport.update({
  id: '/teacher/upload',
  path: '/teacher/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/teacher/reports',
  path: '/teacher/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherQaRoute = TeacherQaRouteImport.update({
  id: '/teacher/qa',
  path: '/teacher/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsLevelRoute = LevelsLevelRouteImport.update({
  id: '/levels/$level',
  path: '/levels/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionBankRoute = AdminQuestionBankRouteImport.update({
  id: '/admin/question-bank',
  path: '/admin/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTestsIndexRoute = TeacherTestsIndexRouteImport.update({
  id: '/teacher/tests/',
  path: '/teacher/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherCoursesIndexRoute = TeacherCoursesIndexRouteImport.update({
  id: '/teacher/courses/',
  path: '/teacher/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassesIndexRoute = TeacherClassesIndexRouteImport.update({
  id: '/teacher/classes/',
  path: '/teacher/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsIndexRoute = AdminExamsIndexRouteImport.update({
  id: '/admin/exams/',
  path: '/admin/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTestsTestIdRoute = TeacherTestsTestIdRouteImport.update({
  id: '/teacher/tests/$testId',
  path: '/teacher/tests/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassesClassIdRoute = TeacherClassesClassIdRouteImport.update({
  id: '/teacher/classes/$classId',
  path: '/teacher/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestsNewRoute = AdminTestsNewRouteImport.update({
  id: '/admin/tests/new',
  path: '/admin/tests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsNewRoute = AdminExamsNewRouteImport.update({
  id: '/admin/exams/new',
  path: '/admin/exams/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsExamIdRoute = AdminExamsExamIdRouteImport.update({
  id: '/admin/exams/$examId',
  path: '/admin/exams/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsExamIdSubmissionsRoute =
  AdminExamsExamIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AdminExamsExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/teacher/qa': typeof TeacherQaRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/upload': typeof TeacherUploadRoute
  '/courses/': typeof CoursesIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRouteWithChildren
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/tests/new': typeof AdminTestsNewRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/tests/$testId': typeof TeacherTestsTestIdRoute
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/courses/': typeof TeacherCoursesIndexRoute
  '/teacher/tests/': typeof TeacherTestsIndexRoute
  '/admin/exams/$examId/submissions': typeof AdminExamsExamIdSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/teacher/qa': typeof TeacherQaRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/upload': typeof TeacherUploadRoute
  '/courses': typeof CoursesIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRouteWithChildren
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/tests/new': typeof AdminTestsNewRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/tests/$testId': typeof TeacherTestsTestIdRoute
  '/admin/exams': typeof AdminExamsIndexRoute
  '/teacher/classes': typeof TeacherClassesIndexRoute
  '/teacher/courses': typeof TeacherCoursesIndexRoute
  '/teacher/tests': typeof TeacherTestsIndexRoute
  '/admin/exams/$examId/submissions': typeof AdminExamsExamIdSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/teacher/qa': typeof TeacherQaRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/upload': typeof TeacherUploadRoute
  '/courses/': typeof CoursesIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRouteWithChildren
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/tests/new': typeof AdminTestsNewRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/tests/$testId': typeof TeacherTestsTestIdRoute
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/courses/': typeof TeacherCoursesIndexRoute
  '/teacher/tests/': typeof TeacherTestsIndexRoute
  '/admin/exams/$examId/submissions': typeof AdminExamsExamIdSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exams'
    | '/forgot-password'
    | '/login'
    | '/practice'
    | '/admin/question-bank'
    | '/courses/$courseId'
    | '/levels/$level'
    | '/teacher/qa'
    | '/teacher/reports'
    | '/teacher/upload'
    | '/courses/'
    | '/teacher/'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/tests/new'
    | '/teacher/classes/$classId'
    | '/teacher/tests/$testId'
    | '/admin/exams/'
    | '/teacher/classes/'
    | '/teacher/courses/'
    | '/teacher/tests/'
    | '/admin/exams/$examId/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exams'
    | '/forgot-password'
    | '/login'
    | '/practice'
    | '/admin/question-bank'
    | '/courses/$courseId'
    | '/levels/$level'
    | '/teacher/qa'
    | '/teacher/reports'
    | '/teacher/upload'
    | '/courses'
    | '/teacher'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/tests/new'
    | '/teacher/classes/$classId'
    | '/teacher/tests/$testId'
    | '/admin/exams'
    | '/teacher/classes'
    | '/teacher/courses'
    | '/teacher/tests'
    | '/admin/exams/$examId/submissions'
  id:
    | '__root__'
    | '/'
    | '/exams'
    | '/forgot-password'
    | '/login'
    | '/practice'
    | '/admin/question-bank'
    | '/courses/$courseId'
    | '/levels/$level'
    | '/teacher/qa'
    | '/teacher/reports'
    | '/teacher/upload'
    | '/courses/'
    | '/teacher/'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/tests/new'
    | '/teacher/classes/$classId'
    | '/teacher/tests/$testId'
    | '/admin/exams/'
    | '/teacher/classes/'
    | '/teacher/courses/'
    | '/teacher/tests/'
    | '/admin/exams/$examId/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamsRoute: typeof ExamsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRoute
  AdminQuestionBankRoute: typeof AdminQuestionBankRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  LevelsLevelRoute: typeof LevelsLevelRoute
  TeacherQaRoute: typeof TeacherQaRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherUploadRoute: typeof TeacherUploadRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  AdminExamsExamIdRoute: typeof AdminExamsExamIdRouteWithChildren
  AdminExamsNewRoute: typeof AdminExamsNewRoute
  AdminTestsNewRoute: typeof AdminTestsNewRoute
  TeacherClassesClassIdRoute: typeof TeacherClassesClassIdRoute
  TeacherTestsTestIdRoute: typeof TeacherTestsTestIdRoute
  AdminExamsIndexRoute: typeof AdminExamsIndexRoute
  TeacherClassesIndexRoute: typeof TeacherClassesIndexRoute
  TeacherCoursesIndexRoute: typeof TeacherCoursesIndexRoute
  TeacherTestsIndexRoute: typeof TeacherTestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/upload': {
      id: '/teacher/upload'
      path: '/teacher/upload'
      fullPath: '/teacher/upload'
      preLoaderRoute: typeof TeacherUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/teacher/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/qa': {
      id: '/teacher/qa'
      path: '/teacher/qa'
      fullPath: '/teacher/qa'
      preLoaderRoute: typeof TeacherQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$level': {
      id: '/levels/$level'
      path: '/levels/$level'
      fullPath: '/levels/$level'
      preLoaderRoute: typeof LevelsLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/question-bank': {
      id: '/admin/question-bank'
      path: '/admin/question-bank'
      fullPath: '/admin/question-bank'
      preLoaderRoute: typeof AdminQuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/tests/': {
      id: '/teacher/tests/'
      path: '/teacher/tests'
      fullPath: '/teacher/tests/'
      preLoaderRoute: typeof TeacherTestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/courses/': {
      id: '/teacher/courses/'
      path: '/teacher/courses'
      fullPath: '/teacher/courses/'
      preLoaderRoute: typeof TeacherCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/classes/': {
      id: '/teacher/classes/'
      path: '/teacher/classes'
      fullPath: '/teacher/classes/'
      preLoaderRoute: typeof TeacherClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams/': {
      id: '/admin/exams/'
      path: '/admin/exams'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AdminExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/tests/$testId': {
      id: '/teacher/tests/$testId'
      path: '/teacher/tests/$testId'
      fullPath: '/teacher/tests/$testId'
      preLoaderRoute: typeof TeacherTestsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/classes/$classId': {
      id: '/teacher/classes/$classId'
      path: '/teacher/classes/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof TeacherClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tests/new': {
      id: '/admin/tests/new'
      path: '/admin/tests/new'
      fullPath: '/admin/tests/new'
      preLoaderRoute: typeof AdminTestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams/new': {
      id: '/admin/exams/new'
      path: '/admin/exams/new'
      fullPath: '/admin/exams/new'
      preLoaderRoute: typeof AdminExamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams/$examId': {
      id: '/admin/exams/$examId'
      path: '/admin/exams/$examId'
      fullPath: '/admin/exams/$examId'
      preLoaderRoute: typeof AdminExamsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams/$examId/submissions': {
      id: '/admin/exams/$examId/submissions'
      path: '/submissions'
      fullPath: '/admin/exams/$examId/submissions'
      preLoaderRoute: typeof AdminExamsExamIdSubmissionsRouteImport
      parentRoute: typeof AdminExamsExamIdRoute
    }
  }
}

interface AdminExamsExamIdRouteChildren {
  AdminExamsExamIdSubmissionsRoute: typeof AdminExamsExamIdSubmissionsRoute
}

const AdminExamsExamIdRouteChildren: AdminExamsExamIdRouteChildren = {
  AdminExamsExamIdSubmissionsRoute: AdminExamsExamIdSubmissionsRoute,
}

const AdminExamsExamIdRouteWithChildren =
  AdminExamsExamIdRoute._addFileChildren(AdminExamsExamIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamsRoute: ExamsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRoute,
  AdminQuestionBankRoute: AdminQuestionBankRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  LevelsLevelRoute: LevelsLevelRoute,
  TeacherQaRoute: TeacherQaRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherUploadRoute: TeacherUploadRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  AdminExamsExamIdRoute: AdminExamsExamIdRouteWithChildren,
  AdminExamsNewRoute: AdminExamsNewRoute,
  AdminTestsNewRoute: AdminTestsNewRoute,
  TeacherClassesClassIdRoute: TeacherClassesClassIdRoute,
  TeacherTestsTestIdRoute: TeacherTestsTestIdRoute,
  AdminExamsIndexRoute: AdminExamsIndexRoute,
  TeacherClassesIndexRoute: TeacherClassesIndexRoute,
  TeacherCoursesIndexRoute: TeacherCoursesIndexRoute,
  TeacherTestsIndexRoute: TeacherTestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
