/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as LevelsLevelRouteImport } from './routes/levels.$level'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'

const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsLevelRoute = LevelsLevelRouteImport.update({
  id: '/levels/$level',
  path: '/levels/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exams'
    | '/courses/$courseId'
    | '/levels/$level'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exams' | '/courses/$courseId' | '/levels/$level' | '/courses'
  id:
    | '__root__'
    | '/'
    | '/exams'
    | '/courses/$courseId'
    | '/levels/$level'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamsRoute: typeof ExamsRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  LevelsLevelRoute: typeof LevelsLevelRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$level': {
      id: '/levels/$level'
      path: '/levels/$level'
      fullPath: '/levels/$level'
      preLoaderRoute: typeof LevelsLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamsRoute: ExamsRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  LevelsLevelRoute: LevelsLevelRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
