/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as TeacherUploadRouteImport } from './routes/teacher.upload'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as LevelsLevelRouteImport } from './routes/levels.$level'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as TeacherExamsIndexRouteImport } from './routes/teacher.exams.index'
import { Route as TeacherClassesIndexRouteImport } from './routes/teacher.classes.index'
import { Route as TeacherExamsNewRouteImport } from './routes/teacher.exams.new'
import { Route as TeacherClassesClassIdRouteImport } from './routes/teacher.classes.$classId'

const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherUploadRoute = TeacherUploadRouteImport.update({
  id: '/teacher/upload',
  path: '/teacher/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/teacher/reports',
  path: '/teacher/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsLevelRoute = LevelsLevelRouteImport.update({
  id: '/levels/$level',
  path: '/levels/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherExamsIndexRoute = TeacherExamsIndexRouteImport.update({
  id: '/teacher/exams/',
  path: '/teacher/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassesIndexRoute = TeacherClassesIndexRouteImport.update({
  id: '/teacher/classes/',
  path: '/teacher/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherExamsNewRoute = TeacherExamsNewRouteImport.update({
  id: '/teacher/exams/new',
  path: '/teacher/exams/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassesClassIdRoute = TeacherClassesClassIdRouteImport.update({
  id: '/teacher/classes/$classId',
  path: '/teacher/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/upload': typeof TeacherUploadRoute
  '/courses/': typeof CoursesIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/exams/new': typeof TeacherExamsNewRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/exams/': typeof TeacherExamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/upload': typeof TeacherUploadRoute
  '/courses': typeof CoursesIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/exams/new': typeof TeacherExamsNewRoute
  '/teacher/classes': typeof TeacherClassesIndexRoute
  '/teacher/exams': typeof TeacherExamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/upload': typeof TeacherUploadRoute
  '/courses/': typeof CoursesIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/exams/new': typeof TeacherExamsNewRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/exams/': typeof TeacherExamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exams'
    | '/courses/$courseId'
    | '/levels/$level'
    | '/teacher/reports'
    | '/teacher/upload'
    | '/courses/'
    | '/teacher/'
    | '/teacher/classes/$classId'
    | '/teacher/exams/new'
    | '/teacher/classes/'
    | '/teacher/exams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exams'
    | '/courses/$courseId'
    | '/levels/$level'
    | '/teacher/reports'
    | '/teacher/upload'
    | '/courses'
    | '/teacher'
    | '/teacher/classes/$classId'
    | '/teacher/exams/new'
    | '/teacher/classes'
    | '/teacher/exams'
  id:
    | '__root__'
    | '/'
    | '/exams'
    | '/courses/$courseId'
    | '/levels/$level'
    | '/teacher/reports'
    | '/teacher/upload'
    | '/courses/'
    | '/teacher/'
    | '/teacher/classes/$classId'
    | '/teacher/exams/new'
    | '/teacher/classes/'
    | '/teacher/exams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamsRoute: typeof ExamsRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  LevelsLevelRoute: typeof LevelsLevelRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherUploadRoute: typeof TeacherUploadRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherClassesClassIdRoute: typeof TeacherClassesClassIdRoute
  TeacherExamsNewRoute: typeof TeacherExamsNewRoute
  TeacherClassesIndexRoute: typeof TeacherClassesIndexRoute
  TeacherExamsIndexRoute: typeof TeacherExamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/upload': {
      id: '/teacher/upload'
      path: '/teacher/upload'
      fullPath: '/teacher/upload'
      preLoaderRoute: typeof TeacherUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/teacher/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$level': {
      id: '/levels/$level'
      path: '/levels/$level'
      fullPath: '/levels/$level'
      preLoaderRoute: typeof LevelsLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/exams/': {
      id: '/teacher/exams/'
      path: '/teacher/exams'
      fullPath: '/teacher/exams/'
      preLoaderRoute: typeof TeacherExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/classes/': {
      id: '/teacher/classes/'
      path: '/teacher/classes'
      fullPath: '/teacher/classes/'
      preLoaderRoute: typeof TeacherClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/exams/new': {
      id: '/teacher/exams/new'
      path: '/teacher/exams/new'
      fullPath: '/teacher/exams/new'
      preLoaderRoute: typeof TeacherExamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/classes/$classId': {
      id: '/teacher/classes/$classId'
      path: '/teacher/classes/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof TeacherClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamsRoute: ExamsRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  LevelsLevelRoute: LevelsLevelRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherUploadRoute: TeacherUploadRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherClassesClassIdRoute: TeacherClassesClassIdRoute,
  TeacherExamsNewRoute: TeacherExamsNewRoute,
  TeacherClassesIndexRoute: TeacherClassesIndexRoute,
  TeacherExamsIndexRoute: TeacherExamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
